# Generated by Django 5.0.3 on 2024-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_tag_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="ppoi",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
