# Generated by Django 5.0.3 on 2024-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_remove_post_ppoi_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=2000),
        ),
    ]
